debug: false
config-path: ~/Documents/Arbeit/Projects/PhpStorm/PhotoPrism/photoprism
cache-path: ~/Documents/Arbeit/Projects/PhpStorm/PhotoPrism/assets/cache
assets-path: ~/Documents/Arbeit/Projects/PhpStorm/PhotoPrism/assets
resources-path: ~/Documents/Arbeit/Projects/PhpStorm/PhotoPrism/assets/resources
originals-path: ~/Documents/Arbeit/Projects/PhpStorm/PhotoPrism/assets/photos/originals
import-path: ~/Documents/Arbeit/Projects/PhpStorm/PhotoPrism/assets/photos/import
export-path: ~/Documents/Arbeit/Projects/PhpStorm/PhotoPrism/assets/photos/export
sql-host: localhost
sql-port: 4000
sql-password: photoprism
http-host:
http-mode: release
http-port: 2342
http-password:
database-driver: internal
database-dsn: root:photoprism@tcp(localhost:4000)/photoprism?parseTime=true
pid-filename: ~/Documents/Arbeit/Projects/PhpStorm/PhotoPrism/photoprism.pid
log-filename: ~/Documents/Arbeit/Projects/PhpStorm/PhotoPrism/photoprism.log
detach-server: false
